org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true
org.gradle.parallel=true

minecraft_version=1.21.11
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.141.4+1.21.11
cloth_config_version=21.11.153
modmenu_version=17.0.0
jade_version=21.1.6+fabric

mod_version=1.0.17-beta1
maven_group=com.smalldaydc.friendcreeper
