package com.smalldaydc.friendcreeper.mixin;

import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
import com.llamalad7.mixinextras.injector.wrapoperation.WrapOperation;
import com.smalldaydc.friendcreeper.ITamedCreeper;
import net.minecraft.entity.LivingEntity;
import net.minecraft.entity.damage.DamageSource;
import net.minecraft.entity.mob.CreeperEntity;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.loot.LootTable;
import net.minecraft.registry.RegistryKey;
import net.minecraft.server.world.ServerWorld;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;

import java.util.function.Consumer;

@Mixin(LivingEntity.class)
public abstract class MixinLivingEntity {

    /**
     * For tamed creepers, wrap the loot consumer so each gunpowder stack
     * generated by the vanilla creeper loot table is replaced with a poppy
     * stack of the same count. This preserves vanilla's drop count / looting
     * distribution exactly — we only swap the item type.
     */
    @WrapOperation(method = "dropLoot(Lnet/minecraft/server/world/ServerWorld;Lnet/minecraft/entity/damage/DamageSource;ZLnet/minecraft/registry/RegistryKey;)V",
                   at = @At(value = "INVOKE",
                            target = "Lnet/minecraft/entity/LivingEntity;generateLoot(Lnet/minecraft/server/world/ServerWorld;Lnet/minecraft/entity/damage/DamageSource;ZLnet/minecraft/registry/RegistryKey;Ljava/util/function/Consumer;)V"))
    private void friendcreeper$swapGunpowderForPoppyOnTamedCreeper(LivingEntity self,
                                                                    ServerWorld world,
                                                                    DamageSource source,
                                                                    boolean causedByPlayer,
                                                                    RegistryKey<LootTable> key,
                                                                    Consumer<ItemStack> consumer,
                                                                    Operation<Void> original) {
        if (self instanceof CreeperEntity creeper
                && ((ITamedCreeper) (Object) creeper).friendcreeper$isTamed()) {
            Consumer<ItemStack> wrapped = stack -> {
                if (stack.isOf(Items.GUNPOWDER)) {
                    consumer.accept(new ItemStack(Items.POPPY, stack.getCount()));
                } else {
                    consumer.accept(stack);
                }
            };
            original.call(self, world, source, causedByPlayer, key, wrapped);
            return;
        }
        original.call(self, world, source, causedByPlayer, key, consumer);
    }
}
